#!/usr/bin/env python3

import argparse
import os


parser = argparse.ArgumentParser()

parser.add_argument("-s", "--sequence", help="fasta/vcf file contains aligned taxa sequences")
parser.add_argument("-a", "--ancseq", help="fasta/vcf file contains aligned ancestral sequences")
parser.add_argument("-x", "--xmx", default="4G", help="Java Xmx setting, e.g.,1G,8G")
parser.add_argument("-o", "--outputdir", default="/home", help="output file directory")

args = parser.parse_args()

exec_dir = os.path.dirname(__file__)

# cmd = "java -jar " + "-Xmx" + args.xmx + " " + exec_dir + "/TIPars.jar " + args.sequence + " " + args.ancseq
cmd = f"java -jar -Xmx{args.xmx} {exec_dir}/TIPars.jar {args.sequence} {args.ancseq} {args.outputdir}"

os.system(cmd)
